rvm:
  - 2.2
  - 2.1
  - 2.0
  - rbx-2.9
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

git:
  submodules: false

env:
  - CONCURRENCY=celluloid-io
  - CONCURRENCY=faye-websocket
